name: Build r77 Rootkit (SLNX)

on: 
  workflow_dispatch: # Кнопка ручного запуска

jobs:
  build:
    runs-on: windows-2022

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '9.0.x' # .NET SDK умеет читать файлы .slnx

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore Packages (SLNX compatible)
      run: dotnet restore r77.slnx

    - name: Build x64 Configuration
      run: msbuild r77.slnx /p:Configuration=Release /p:Platform=x64

    - name: Build x86 Configuration
      run: msbuild r77.slnx /p:Configuration=Release /p:Platform=x86

    - name: Upload Compiled Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: r77-built-output
        path: |
          **/Release/
          **/bin/Release/
          **/x64/Release/
          **/Win32/Release/
